Movie/app/home/forms.py
# !/user/bin/env python
# -*- coding:utf-8 -*- 
# time: 2020/3/7--19:52
__author__ = 'Henry'


from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, TextAreaField, FileField, SelectField,SelectMultipleField
from wtforms.validators import DataRequired, ValidationError,EqualTo,Email,Regexp
from app.models import Admin, Tag,Auth,Role,User
from flask import session


class RegistForm(FlaskForm):
    '''会员注册表单'''
    name = StringField(
        label='昵称',
        validators=[
            DataRequired('请输入昵称!')
        ],
        description='昵称',
        render_kw={
            'class' :'form-control input-lg',
            'placeholder':'昵称',
            # 'required':'required'
        }
    )
    email = StringField(
        label='邮箱',
        validators=[
            DataRequired('请输入邮箱!'),
            Email('邮箱格式不正确!')   #Email模块验证邮箱格式
        ],
        description='邮箱',
        render_kw={
            'class': 'form-control input-lg',
            'placeholder': '邮箱',
            # 'required': 'required'
        }
    )
    phone = StringField(
        label='手机',
        validators=[
            DataRequired('请输入手机号!'),
            Regexp('1[3458]\\d{9}',message='手机格式不正确!')   #Regexp正则模块验证手机格式(第一位:1;第二位:3或4或5或8;加上后面9位数)
        ],
        description='手机',
        render_kw={
            'class': 'form-control input-lg',
            'placeholder': '手机',
            # 'required': 'required'
        }
    )
    pwd = PasswordField(
        label='密码',
        validators=[
            DataRequired('请输入密码!')
        ],
        description='密码',
        render_kw={
            'class': 'form-control input-lg',
            'placeholder': '密码',
            # 'required': 'required'
        }
    )
    repwd = PasswordField(
        label='确认密码',
        validators=[
            DataRequired('请输入确认密码!'),
            EqualTo('pwd','两次密码输入不一致!')
        ],
        description='确认密码',
        render_kw={
            'class': 'form-control input-lg',
            'placeholder': '确认密码',
            # 'required': 'required'
        }
    )
    submit = SubmitField(
        '注册',
        render_kw={
            'class': 'btn btn-lg btn-success btn-block'
        }
    )
    #通过下面的验证函数不好使,还是放在views中验证比较好!
    def validata_name(self,field):
        '''查询用户名是否存在'''
        name = field.data
        user = User.query.filter_by(name=name).count()
        if user == 1:
            raise ValidationError('此昵称已存在!')


    def validata_email(self,field):
        '''查询邮箱是否存在'''
        email = field.data
        user = User.query.filter_by(email=email).count()
        if user == 1:
            raise ValidationError('此邮箱已存在!')

    def validata_phone(self,field):
        '''查询手机是否存在'''
        phone = field.data
        user = User.query.filter_by(phone=phone).count()
        if user == 1:
            raise ValidationError('此手机号已存在!')


class LoginForm(FlaskForm):
    '''会员登录表单'''
    name = StringField(
        label='账号',
        validators=[
            DataRequired('请输入账号!')
        ],
        description='账号',
        render_kw={
            'class': 'form-control input-lg',
            'placeholder': '用户名',
            'required': 'required'
        }
    )
    pwd = PasswordField(
        label='密码',
        validators=[
            DataRequired('请输入密码!')
        ],
        description='密码',
        render_kw={
            'class': 'form-control input-lg',
            'placeholder': '密码',
            'required': 'required'
        }
    )
    submit = SubmitField(
        '登录',
        render_kw={
            'class': 'btn btn-lg btn-success btn-block'
        }
    )


class UserdetailForm(FlaskForm):
    '''会员修改资料表单'''
    name = StringField(
        label='昵称',
        validators=[
            DataRequired('请输入昵称!'),
        ],
        description='昵称',
        render_kw={
            'class': 'form-control'
        }
    )
    email = StringField(
        label='邮箱',
        validators=[
            DataRequired('请输入邮箱!'),
            Email('邮箱格式不正确!')  # Email模块验证邮箱格式
        ],
        description='邮箱',
        render_kw={
            'class': 'form-control'
        }
    )
    phone = StringField(
        label='手机',
        validators=[
            DataRequired('请输入手机号!'),
            Regexp('1[3458]\\d{9}', message='手机格式不正确!')  # Regexp正则模块验证手机格式(第一位:1;第二位:3或4或5或8;加上后面9位数)
        ],
        description='手机',
        render_kw={
            'class': 'form-control'
        }
    )
    face = FileField(
        label='头像',
        description='头像',
    )
    info = TextAreaField(
        label='简介',
        description='简介',
        render_kw={
            'class': 'form-control',
            'rows':10
        }
    )
    submit = SubmitField(
        '保存修改',
        render_kw={
            'class': 'btn btn-success'
        }
    )


class PwdForm(FlaskForm):
    '''修改用户密码表单'''
    old_pwd = PasswordField(
        label='旧密码',
        validators=[
            DataRequired('请输入旧密码!'),
        ],
        description='旧密码',
        render_kw={
            'class': 'form-control',
            'placeholder':'旧密码',
            'required':'required'
        }
    )
    new_pwd = PasswordField(
        label='新密码',
        validators=[
            DataRequired('请输入新密码!'),
        ],
        description='新密码',
        render_kw={
            'class': 'form-control',
            'placeholder': '新密码',
            'required': 'required'
        }
    )
    submit = SubmitField(
        '修改密码',
        render_kw={
            'class': 'btn btn-success'
        }
    )


class CommentForm(FlaskForm):
    '''提交电影评论表单'''
    content = TextAreaField(
        label='评论内容',
        description='内容',
        validators=[
            DataRequired('请输入评论内容!')
        ],
        render_kw={
            # 'id':'input_content',   #原版:带表情的评论框
            'id':'comment',
            'rows': 5
        }
    )
    submit = SubmitField(
        '提交评论',
        render_kw={
            'class': 'btn btn-success',
            'id': 'btn-sub',
        }
    )

Movie/app/home/__init__.py
# !/user/bin/env python
# -*- coding:utf-8 -*- 
# time: 2020/3/7--19:51
__author__ = 'Henry'

from flask import Blueprint

home = Blueprint('home',__name__)

import app.home.views

Movie/app/home/views.py
# !/user/bin/env python
# -*- coding:utf-8 -*- 
# time: 2020/3/7--19:52
__author__ = 'Henry'

from . import home
from flask import render_template, url_for, redirect, flash, session, request
from app.home.forms import RegistForm, LoginForm, UserdetailForm, PwdForm,CommentForm
from app.models import User, Userlog, Comment, Movie,Preview,Tag,Moviecol
from app import db, app
import uuid  # 添加唯一标志符
from werkzeug.security import generate_password_hash
from functools import wraps  # 装饰器(用于访问控制)
from werkzeug.utils import secure_filename
import os, stat, datetime

# 修改上传的文件名称
def change_filename(filename):
    # fileinfo = os.path.splitext(filename)  # 取出上传的文件名的后缀(.MP4)
    fileinfo = filename.split('.')  # 取出上传的文件名的后缀(.MP4)
    filename = datetime.datetime.now().strftime('%Y%m%d%H%M%S') + str(uuid.uuid4().hex) + '.' + fileinfo[-1]
    return filename


# 前台登录装饰器(只能登录后才能访问会员中心)
def user_login_req(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'user' not in session:  # if session['user'] is None:
            return redirect(url_for('home.login', next=request.url))
        return f(*args, **kwargs)

    return decorated_function


# 首页重定向
@home.route('/',methods=['GET'])
def index_1():
    return redirect('/1/')

# 首页
@home.route('/<int:page>/',methods=['GET'])
def index(page=None):
    #电影筛选 (默认按视频上传时间排,最新上传的在最前面)
    tags = Tag.query.all()
    page_data = Movie.query.order_by(
        Movie.addtime.desc()
    )
    # 1.电影标签(国产,动漫,科技...)
    tid = request.args.get('tid',0)
    if int(tid) != 0:
        page_data = page_data.filter_by(tag_id=int(tid))

    # 2.电影星级(一星到五星)
    star = request.args.get('star',0)
    if int(star) != 0:
        page_data = page_data.filter_by(star=int(star))

    # 3.添加时间(最近,最早)
    time = request.args.get('time',0)
    if int(time) != 0:
        if int(time) == 1: #降序(最近)
            page_data = Movie.query.order_by(
                Movie.addtime.desc()
            )
        else: #升序(最早) if int(time) == 2
            page_data = Movie.query.order_by(
                Movie.addtime.asc()
            )

    # 4.播放数量(从高到低,从低到高)
    pm = request.args.get('pm',0)
    if int(pm) != 0:
        if int(pm) == 1:
            page_data = Movie.query.order_by(
                Movie.playnum.desc()
            )
        else:
            page_data = Movie.query.order_by(
                Movie.playnum.asc()
            )

    # 5.评论数量(从高到低,从低到高)
    cm = request.args.get('cm',0)
    if int(cm) != 0:
        if int(cm) == 1:
            page_data = Movie.query.order_by(
                Movie.commentnum.desc()
            )
        else:
            page_data = Movie.query.order_by(
                Movie.commentnum.asc()
            )

    if page == None:
        page =1
    page_data = page_data.paginate(page=page,per_page=10)
    #将上面接受到的参数组成一个字典p
    p = dict(
        tid=tid,
        star=star,
        time=time,
        pm=pm,
        cm=cm
    )
    return render_template('home/index.html',tags=tags,p=p,page_data=page_data)


# 登录
@home.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        data = form.data
        user = User.query.filter_by(name=data['name']).first()
        if not user:
            flash('没有此用户名!','err')
            return redirect(url_for('home.login'))
        if user.check_pwd(data['pwd']) ==False:  # 验证密码是否正确
            flash('密码错误!', 'err')
            return redirect(url_for('home.login'))
        # 登录成功则保存会话:
        session['user'] = user.name  # 用户名
        session['user_id'] = user.id  # 用户ID
        # 将登录操作存入会员登陆日志
        userlog = Userlog(
            user_id=session['user_id'],
            ip=request.remote_addr
        )
        db.session.add(userlog)
        db.session.commit()
        return redirect(url_for('home.user'))  # 登录成功跳到会员中心
    return render_template('home/login.html', form=form)


# 登出
@home.route('/logout/')
def logout():
    # 删除会话
    session.pop('user', None)
    session.pop('user_id', None)
    return redirect(url_for('home.login'))


# 注册
@home.route('/regist/', methods=['GET', 'POST'])
def regist():
    form = RegistForm()
    if form.validate_on_submit():
        data = form.data
        #查询用户名是否存在
        name = data['name']
        user = User.query.filter_by(name=name).count()
        if user == 1:
            flash('此昵称已存在!','err')
            return render_template('home/regist.html', form=form)

        email = data['email']
        user = User.query.filter_by(email=email).count()
        if user == 1:
            flash('此邮箱已存在!','err')
            return render_template('home/regist.html', form=form)

        phone = data['phone']
        user = User.query.filter_by(phone=phone).count()
        if user == 1:
            flash('此手机号已存在!','err')
            return render_template('home/regist.html', form=form)

        user = User(
            name=data['name'],
            email=data['email'],
            phone=data['phone'],
            pwd=generate_password_hash(data['pwd']),  # 加密用户的密码
            uuid=uuid.uuid4().hex  # 生成用户的唯一标志符
        )
        db.session.add(user)
        db.session.commit()
        flash('恭喜您,注册成功!', 'ok')
        return redirect(url_for('home.login'))
    return render_template('home/regist.html', form=form)


# 会员中心(可修改会员资料)
@home.route('/user/', methods=['GET', 'POST'])
@user_login_req  # 只有登录后才能访问会员中心
def user():
    form = UserdetailForm()
    user = User.query.get_or_404(session['user_id'])
    form.face.validators = []
    # 获取用户现在的会员信息(get)
    if request.method == 'GET':
        form.name.data = user.name
        form.email.data = user.email
        form.phone.data = user.phone
        form.info.data = user.info
    # 修改会员信息(post)
    if form.validate_on_submit():
        data = form.data
        # 如果用户名以存在,则修改失败
        user_name = User.query.filter_by(name=data['name']).count()
        if user_name == 1 and user.name != data['name']:
            flash('用户昵称已存在,请重新输入!', 'err')
            return redirect(url_for('home.user'))
        # 如果邮箱以存在,则修改失败
        user_email = User.query.filter_by(email=data['email']).count()
        if user_email == 1 and user.email != data['email']:
            flash('邮箱已存在,请重新输入!', 'err')
            return redirect(url_for('home.user'))
        # 如果手机号以存在,则修改失败
        user_phone = User.query.filter_by(phone=data['phone']).count()
        if user_phone == 1 and user.phone != data['phone']:
            flash('手机号已存在,请重新输入!', 'err')
            return redirect(url_for('home.user'))

        # 修改头像
        if not os.path.exists(app.config['FC_DIR']):  # 没有就创建文件夹
            os.makedirs(app.config['FC_DIR'])
            # os.chmod(app.config['FC_DIR'], 'rw')  # 给文件夹可读可写的权限,这样才能保存文件呀
            os.chmod(app.config['FC_DIR'], stat.S_IRWXU)  # 给文件夹可读可写的权限,这样才能保存文件呀 'rw'
        # 如果face不为空,即为修改了头像地址,要重新保存
        # 上传头像文件,一定要加上enctype="multipart/form-data"
        if form.face.data != '':
            file_face = secure_filename(form.face.data.filename)  # 生成上传的电影封面的文件名,并安全加密
            user.face = change_filename(file_face)
            form.face.data.save(app.config['FC_DIR'] + user.face)
        # 修改入库
        user.name = data['name'],
        user.email = data['email'],
        user.phone = data['phone'],
        user.info = data['info'],
        db.session.add(user)
        db.session.commit()
        flash('修改资料成功!', 'ok')
        return redirect(url_for('home.user'))
    return render_template('home/user.html', form=form, user=user)


# 1.修改密码
@home.route('/pwd/', methods=['GET', 'POST'])
@user_login_req
def pwd():
    form = PwdForm()
    user = User.query.filter_by(id=session['user_id']).first()
    if form.validate_on_submit():
        data = form.data
        if not user.check_pwd(data['old_pwd']):
            flash('旧密码错误!请重新输入!', 'err')
            return redirect(url_for('home.pwd'))
        user.pwd = generate_password_hash(data['new_pwd'])
        db.session.add(user)
        db.session.commit()
        flash('修改密码成功!', 'ok')
        return redirect(url_for('home.logout'))
    return render_template('home/pwd.html', form=form)


# 2.评论记录
@home.route('/comments/<int:page>/', methods=['GET'])
@user_login_req
def comments(page=None):
    if page == None:
        page = 1
    page_data = Comment.query.join(
        User
    ).join(
        Movie
    ).filter(
        Comment.user_id == session['user_id'],
        User.id == Comment.user_id,
        Movie.id == Comment.movie_id
    ).order_by(
        Comment.addtime.desc()
    ).paginate(page=page, per_page=6)
    return render_template('home/comments.html', page_data=page_data)


# 3.登录日志
@home.route('/loginlog/<int:page>/', methods=['GET'])
@user_login_req
def loginlog(page=None):
    if page == None:
        page = 1
    page_data = Userlog.query.filter_by(
        user_id=session['user_id']
    ).order_by(
        Userlog.addtime.desc()
    ).paginate(page=page, per_page=10)
    return render_template('home/loginlog.html', page_data=page_data)


# 4.电影收藏
@home.route('/moviecol/<int:page>/',methods=['GET'])
@user_login_req
def moviecol(page=None):
    if page == None:
        page = 1
    page_data = Moviecol.query.join(
        Movie
    ).filter(
        Moviecol.user_id == session['user_id']
    ).order_by(
        Moviecol.addtime.desc()
    ).paginate(page=page,per_page=10)
    return render_template('home/moviecol.html',page_data=page_data)


#添加电影收藏(AJAX异步方法)
@home.route('/moviecol/add/',methods=['GET'])
@user_login_req
def moviecol_add():
    #接受uid用户ID和mid电影ID
    uid = request.args.get("uid","")
    mid = request.args.get("mid","")
    moviecol = Moviecol.query.filter_by(
        # user_id = int(uid),
        # movie_id = int(mid)
        movie_id = mid,
        user_id = uid
    ).count()
    if moviecol == 1:  #如果该用户已经收藏了该电影
        data = dict(ok=0)
    # if moviecol == 0:  #没有收藏就要收藏
    else:
        moviecol = Moviecol(
            movie_id=mid,
            user_id=uid
        )

Movie/app/templates/home/animation.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>热门视频</title>
<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='anim/css/style.css') }}">
</head>
<body>
<!--轮播图 开始 -->
<div class="main_banner">
	<div class="main_banner_wrap">
{#		<canvas id="myCanvas" width="150" height="150"></canvas>#}  {# 有闹钟特效 #}
		<canvas id="myCanvas" width="0" height="0"></canvas>
		<div class="main_banner_box" id="m_box">
			<a href="javascript:void(0)" class="banner_btn js_pre">
				<span class="banner_btn_arrow"><i></i></span>
			</a>
			<a href="javascript:void(0)" class="banner_btn btn_next js_next">
				<span class="banner_btn_arrow"><i></i></span>
			</a>
			<ul>
                {% for v in data %}
				<li id="imgCard{{ v.id-1 }}">  {# 因为是从imgCard0到imgCard5,一共6张图#}
{#					<a href="{{ url_for('home.play',id=v.id,page=1) }}" target="_blank">#}
					<a href="{{ url_for('home.play',id=v.id,page=1 )}}" target="_blank">
{#					<a href=""><span style="opacity:0;"></span></a>#}
					<img src="{{ url_for('static',filename='uploads/' + v.logo) }}" alt="">
					<p style="bottom:0">{{ v.title }}</p>
                        <span style="opacity:0;"></span></a>
				</li>
                {% endfor %}
			</ul>
			<!--火狐倒影图层-->
{#			<p id="rflt"></p>#}
			<!--火狐倒影图层-->
		</div>
		<!--序列号按钮-->
		<div class="btn_list">
			<span class="curr"></span><span></span><span></span><span></span><span></span>
		</div>
	</div>

</div>
<!--轮播图 结束 -->

<script type="text/javascript" src="{{ url_for('static',filename='anim/js/jquery.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static',filename='anim/js/script.js') }}"></script>

</body>
</html>

Movie/app/templates/home/home.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>大豪Video</title>
    <link rel="shortcut icon" href="{{ url_for('static',filename='base/images/logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/bootstrap-movie.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/animate.css') }}">
     <link type="text/css" rel="stylesheet" href="{{ url_for('static',filename='music/css/player.css') }}">

<script src="//libs.baidu.com/jquery/1.10.2/jquery.min.js"></script>
<script type="text/javascript" src="{{ url_for('static',filename='base/js/jquery.goup.min.js') }}"></script>

    <style>
        .navbar-brand > img {
            display: inline;
        }

        .media {
            padding: 3px;
            border: 1px solid #ccc
        }

    </style>
    {% block css %}{% endblock %}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{ url_for('home.index',page=1) }}" class="navbar-brand" style="width:250px;">
                <img src="{{ url_for('static',filename='base/images/logo.png') }}" style="height:30px;">&nbsp;豪豪视频
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入视频名！" id="key_movie">
                    <span class="input-group-btn">
                        <a id="do_search" class="btn btn-default"><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{ url_for('home.index',page=1) }}"><span
                            class="glyphicon glyphicon-film"></span>&nbsp;首页</a>
                </li>
                {% if 'user' not in session %}
                    <li>
                        <a class="curlink" href="{{ url_for('home.login') }}"><span
                                class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                    </li>
                    <li>
                        <a class="curlink" href="{{ url_for('home.regist') }}"><span
                                class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                    </li>
                {% endif %}

                {% if 'user' in session %}

                    <li>
                        <a class="curlink" href="{{ url_for('home.logout') }}"><span
                                class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                    </li>
                    <li>
                        <a class="curlink" href="{{ url_for('home.user') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;个人中心</a>
                    </li>
                {% endif %}
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->
<div class="container" style="margin-top:76px">
    {% block content %}{% endblock %}
</div>
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;2020&nbsp;flaskmovie.<a href="https://github.com/Henryhaohao">Henry</a>..毕业设计
                </p>
            </div>
        </div>
    </div>
</footer>



<!--底部-->
<script src="{{ url_for('static',filename='base/js/jquery.min.js') }}"></script>
<script src="{{ url_for('static',filename='base/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static',filename='base/js/jquery.singlePageNav.min.js') }}"></script>
<script src="{{ url_for('static',filename='base/js/wow.min.js') }}"></script>
<script src="{{ url_for('static',filename='lazyload/jquery.lazyload.min.js') }}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>


<script>
    $(function () {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function () {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
        {#点击搜索,触发事件,跳转到搜索页面#}
        $('#do_search').click(function () {
            var key = $('#key_movie').val();
            location.href = '{{ url_for('home.search',page=1) }}?key=' + key;
        });
        $.goup({
            trigger: 100,
            bottomOffset: 30, /*图标距离底边的边距*/
            locationOffset: 30, /*图标距离右边的边距*/
            title: '', /*图标下面的文字*/
            titleAsText: true
        });
    });
</script>

{#<script>#}
{#    $(document).ready(function () {#}
{#        $.goup({#}
{#            trigger: 100,#}
{#            bottomOffset: 30, /*图标距离底边的边距*/#}
{#            locationOffset: 30, /*图标距离右边的边距*/#}
{#            title: '', /*图标下面的文字*/#}
{#            titleAsText: true#}
{#        });#}
{#    });#}
{#</script>#}

{% block js %}{% endblock %}

</body>
</html>

Movie/app/templates/home/loginlog.html
{% extends 'home/home.html' %}

{% import 'ui/home_page.html' as pg %}

{% block content %}
    {% include 'home/menu.html' %}
    <div class="col-md-9">
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="glyphicon glyphicon-map-marker"></span>&nbsp;登录日志</h3>
            </div>
            <div class="panel-body">
                <table class="table table-bordered">
                    <tr>
                        <td style="width:10%">编号</td>
                        <td style="width:30%">登录时间</td>
                        <td style="width:30%">登录IP</td>
                    {# <td style="width:30%">登录地址</td>#}
                    </tr>
                    {% for v in page_data.items %}
                        <tr>
                            <td>{{ v.id }}</td>
                            <td>{{ v.addtime }}</td>
                            <td>{{ v.ip }}</td>
                        {# <td>云南昆明</td> #}
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-12 text-center">
        {# 引入后台页码模板 #}
        {{ pg.page(page_data,'home.loginlog') }}
    </div>
{% endblock %}

{#添加JS:当鼠标点击模块时,用于激活会员中心的登陆日志模块#}
{% block js %}
    <script>
        $(document).ready(function () {
            $('#m-4').addClass('active');
        });
    </script>
{% endblock %}

Movie/app/templates/home/menu.html
<div class="col-md-3">
    <div class="list-group">
        <a id="m-1" href="{{ url_for('home.user') }}" class="list-group-item">
            <span class="glyphicon glyphicon-user"></span>&nbsp;个人中心
        </a>
        <a id="m-2" href="{{ url_for('home.pwd') }}" class="list-group-item">
            <span class="glyphicon glyphicon-lock"></span>&nbsp;修改密码
        </a>
        <a id="m-3" href="{{ url_for('home.comments',page=1) }}" class="list-group-item">
            <span class="glyphicon glyphicon-comment"></span>&nbsp;评论记录
        </a>
        <a id="m-4" href="{{ url_for('home.loginlog',page=1) }}" class="list-group-item">
            <span class="glyphicon glyphicon-calendar"></span>&nbsp;登录日志
        </a>
        <a id="m-5" href="{{ url_for('home.moviecol',page=1) }}" class="list-group-item">
            <span class="glyphicon glyphicon-heart"></span>&nbsp;收藏视频
        </a>
    </div>
</div>